name: Build & Create Release (Manual)

permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Versão da Release (ex: v1.0.0 ou v1.0.0-Alfa)"
        required: true
        default: "v1.0.0"

jobs:
  build:
    name: Build Executable on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --only-binary :all: --require-hashes -r requirements.txt

      - name: Build Executable (Linux)
        if: runner.os == 'Linux'
        run: |
          python -m PyInstaller --onefile --hidden-import="selenium.webdriver.chrome.options" --name=KahootAuto_linux app.py

      - name: Build Executable (Windows)
        if: runner.os == 'Windows'
        run: |
          python -m PyInstaller --onefile --hidden-import="selenium.webdriver.chrome.options" --name=KahootAuto_win.exe app.py
          
      - name: Upload Artifact (Linux)
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v4
        with:
          name: binary-linux
          path: dist/KahootAuto_linux

      - name: Upload Artifact (Windows)
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: binary-windows
          path: dist/KahootAuto_win.exe

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Linux Artifact
        uses: actions/download-artifact@v4
        with:
          name: binary-linux
          path: ./release-assets

      - name: Download Windows Artifact
        uses: actions/download-artifact@v4
        with:
          name: binary-windows
          path: ./release-assets

      - name: Create Release via GitHub CLI
        run: |
          gh release create "$VERSION" ./release-assets/* --title "Release $VERSION" --notes "Release automatizada contendo os executáveis compilados para Linux e Windows."
        env:
          VERSION: ${{ inputs.version }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
